-- Greenplanet starter data
-- Run this after supabase/schema.sql.

insert into public.products
  (legacy_id, slug, title, brand, category, description, cost, price, stock, sku, image_url, giftbox_eligible, occasions, shape, status)
values
  ('p1', 'linen-baby-sleeper', 'Linen baby sleeper', 'Babyly', 'Baby & barsel', 'Blød babysleeper i hør til en rolig barselsgave.', 345.34, 690.69, 4, 'BABYLY-SLEEPER', 'https://cdn.faire.com/fastly/0a4b47c9202f6e86eb7fc4f9ac12be65afbd26a83c5ea8198f5fc3227639fa68.jpeg', true, ARRAY['Barsel','Baby gave'], 'box', 'live'),
  ('p2', 'linen-babynest', 'Linen babynest', 'Babyly', 'Baby & barsel', 'Linen babynest fra tidligere Faire-bestilling.', 407.93, 815.86, 2, 'BABYLY-NEST', 'https://cdn.faire.com/fastly/81b057e82552add927d1a2040ad353dbb3c89a2244af930cc0dd7a12b7f2137c.jpeg', true, ARRAY['Barsel','Baby gave'], 'box', 'live'),
  ('p3', 'dear-baby-skin-care-kit', 'Dear Baby Skin Care Kit', 'SoKind', 'Baby & barsel', 'Komplet hudplejekit til baby og nybagte forældre.', 284.48, 536.75, 5, '5745000074006', 'https://cdn.faire.com/fastly/bd8a91f05ae745117431e43cfe5ca6a371cc1f4fce212ef45cb89f6814745ed9.jpeg', true, ARRAY['Barsel','Ny mor'], 'bottle', 'live'),
  ('p4', 'belly-sheet-masks', 'Belly Sheet Masks', 'SoKind', 'Baby & barsel', 'Nærende belly sheet masks til graviditets- og barselsgaver.', 138.16, 276.32, 12, '5745000074082', 'https://cdn.faire.com/fastly/d37349ca6195cddcbf7b0302881802dbee0521bdb8a05e422117f7b63d55c327.jpeg', true, ARRAY['Ny mor','Rolig weekend'], 'pouch', 'live'),
  ('p5', 'baby-shampoo-body-wash', 'Baby Shampoo & Body Wash', 'SoKind', 'Baby & barsel', 'Mild shampoo og body wash til baby.', 96.91, 193.83, 8, '5745000074020', 'https://cdn.faire.com/fastly/636f7f3928bd59c52789bcfa73fd1d37dbc5d769617a2d6fec57cef2d6303d35.jpeg', true, ARRAY['Barsel','Baby gave'], 'bottle', 'live'),
  ('p6', 'organic-cuddly-rabbit-white', 'Organic Cuddly Rabbit White', 'Summerville organic', 'Baby & barsel', 'Økologisk cuddly rabbit i hvid.', 66.34, 148.33, 2, '680001', 'https://cdn.faire.com/fastly/c360dff72332ad9e4cafd748a5960597043b7794a3c54ce6370d89a83f147a94.jpeg', true, ARRAY['Barsel','Baby gave'], 'jar', 'live'),
  ('p7', 'organic-cuddly-rabbit-ice-blue', 'Organic Cuddly Rabbit Ice Blue', 'Summerville organic', 'Baby & barsel', 'Økologisk cuddly rabbit i ice blue.', 66.34, 148.33, 2, '680007', 'https://cdn.faire.com/fastly/c11015db21acc7ed1384994bb6501accc7d13c750238e10ec46c5e0b5bb14999.jpeg', true, ARRAY['Barsel','Baby gave'], 'jar', 'live'),
  ('p8', 'hooded-baby-towel-white', 'Hooded Baby Towel White', 'Summerville organic', 'Baby & barsel', 'Økologisk babyhåndklæde med hætte i hvid.', 67.09, 170.70, 2, '600825', 'https://cdn.faire.com/fastly/2945f340f3ecc013ede8569292ea50c3423f2c7da14e8ff062c93fed8e57ae56.jpeg', true, ARRAY['Barsel','Baby gave'], 'box', 'live'),
  ('p9', 'hooded-baby-towel-rabbit-pink', 'Hooded Baby Towel Rabbit Pink', 'Summerville organic', 'Baby & barsel', 'Økologisk babyhåndklæde med kanin-detalje i pink.', 87.96, 207.97, 2, '600882', 'https://cdn.faire.com/fastly/b8cd0ea17ef4435d3572b690f02ff8ba20ea2224604fda66cdb2df5684dacb89.jpeg', true, ARRAY['Barsel','Baby gave'], 'box', 'live'),
  ('p10', 'hooded-baby-towel-rabbit-grey', 'Hooded Baby Towel Rabbit Grey', 'Summerville organic', 'Baby & barsel', 'Økologisk babyhåndklæde med kanin-detalje i grå.', 87.96, 207.97, 2, '600879', 'https://cdn.faire.com/fastly/95f5cd5ac72e9298312585ebc8eab2306fdb06cc4f0e3b614205c600dadb8358.jpeg', true, ARRAY['Barsel','Baby gave'], 'box', 'live'),
  ('p11', 'franse-roze-klei', 'Franse Roze Klei', 'More', 'Naturlig beauty', '100% naturlig fransk rosa ler til wellness-æsker.', 49.58, 118.91, 2, '7442956129115', 'https://cdn.faire.com/fastly/4c3ce9eb94878f5e25df6f9e40ddf14abd1bd592dff1df26a3d1021086d66d6a.jpeg', true, ARRAY['Wellness','Rolig weekend'], 'jar', 'live'),
  ('p12', 'marokkaanse-ghassoul-kleipoeder', 'Marokkaanse Ghassoul Kleipoeder', 'More', 'Naturlig beauty', '100% naturlig ghassoul lerpulver.', 49.58, 118.91, 2, '7442956129139', 'https://cdn.faire.com/fastly/98491dad59eb608744f9aea983f7feeaf86a2ffb51519ecd3ab6b0b23e1238b4.jpeg', true, ARRAY['Wellness','Rolig weekend'], 'jar', 'live'),
  ('p13', 'bulgaarse-rozenwater', 'Bulgaarse rozenwater', 'More', 'Naturlig beauty', 'Økologisk bulgarsk rosenvand til ansigt og hudpleje.', 52.63, 133.82, 2, '8719327521557', 'https://cdn.faire.com/fastly/86c6e142f2bc3d341345044ab2d8947dbe3cfed709927713b5abaa122da6abab.jpeg', true, ARRAY['Wellness','Ny mor'], 'bottle', 'live'),
  ('p14', 'arganolie', 'Arganolie', 'More', 'Naturlig beauty', 'Økologisk og koldpresset arganolie.', 61.95, 148.73, 2, '1', 'https://cdn.faire.com/fastly/c1647a7becd367e3a9a01783053a3d3e20edeb286cb7ee5d3bb3d7ca5b937868.jpeg', true, ARRAY['Wellness','Rolig weekend'], 'bottle', 'live'),
  ('p15', 'rosehip-olie', 'Rosehip olie', 'More', 'Naturlig beauty', 'Økologisk og koldpresset rosehip olie.', 71.27, 171.09, 2, '8720299095168', 'https://cdn.faire.com/fastly/0ae6cc5fc64666b88bd818d984c3c92702695f39d2d69b520ce0f0b2ffa164cd.jpeg', true, ARRAY['Wellness','Ny mor'], 'bottle', 'live'),
  ('p16', 'jojoba-olie', 'Jojoba Olie', 'More', 'Naturlig beauty', 'Økologisk og koldpresset jojobaolie.', 76.26, 186.00, 2, '8720299095137', 'https://cdn.faire.com/fastly/9433451c7afbdc5e0a362368282f6decc233b05183e8f693f0402e1ae1ded286.jpeg', true, ARRAY['Wellness','Rolig weekend'], 'bottle', 'live')
on conflict (legacy_id) do update set
  slug = excluded.slug,
  title = excluded.title,
  brand = excluded.brand,
  category = excluded.category,
  description = excluded.description,
  cost = excluded.cost,
  price = excluded.price,
  stock = excluded.stock,
  sku = excluded.sku,
  image_url = excluded.image_url,
  giftbox_eligible = excluded.giftbox_eligible,
  occasions = excluded.occasions,
  shape = excluded.shape,
  status = excluded.status;

insert into public.giftboxes
  (legacy_id, slug, title, category, description, note, recipient, occasion, packing, card_text, delivery, why, details, box_price, status)
values
  ('g1', 'ny-mor-ro', 'Ny Mor Ro', 'Ny mor', 'En gave med blid hudpleje til den gravide eller nybagte mor.', 'Belly masks, rosenvand og rosehip olie.', 'Til den gravide eller nybagte mor, der fortjener en lille pause.', 'Barsel, babyshower, mors dag eller en omsorgsfuld hilsen.', 'Pakkes i Greenplanet gaveæske med silkepapir, roligt udtryk og mulighed for personlig hilsen.', 'Skriv en kort hilsen ved checkout, så lægger vi den ved i æsken.', 'Kan sendes direkte til modtageren eller til dig, hvis du selv vil overrække gaven.', 'Æsken samler blid kropspleje og små pauser, som kan bruges uden at kræve meget tid eller overskud.', ARRAY['3 produkter','Personligt kort kan tilføjes','Velegnet til direkte gavelevering','Naturlig beauty og barselsro'], 49, 'live'),
  ('g2', 'baby-first-care', 'Baby First Care', 'Barsel', 'Blid babypleje og en lille økologisk ven til den første gave.', 'SoKind plejekit, baby wash og cuddly rabbit.', 'Til nybagte forældre, der gerne vil have en praktisk og smuk startpakke.', 'Barselsbesøg, firmagave, babyshower eller velkommen-til-verden gave.', 'Pakkes som en rolig barselsæske med babypleje for sig og tekstilproduktet synligt i toppen.', 'Mulighed for personlig hilsen, fx fra kollegaer, familie eller vennegruppe.', 'Egnet til levering direkte til familien, og nem at sende som samlet gave.', 'Kombinationen af plejeprodukt og lille blød gave gør æsken både brugbar og personlig.', ARRAY['3 produkter','Blid babypleje','Lille økologisk gave','God som første barselsgave'], 49, 'live'),
  ('g3', 'oekologisk-babybad', 'Økologisk Babybad', 'Baby gave', 'Alt til et blødt babybad samlet i en gaveæske.', 'Hooded towel, baby wash og cuddly rabbit.', 'Til baby og forældre, der kan bruge en praktisk gave med lidt luksus i hverdagen.', 'Barsel, dåb, babyshower eller en lille hverdagsgave.', 'Håndklæde, baby wash og lille ven pakkes sammen, så æsken føles komplet ved udpakning.', 'Tilføj korttekst ved checkout, hvis gaven skal sendes direkte.', 'Kan pakkes som gavelevering med kort og uden prisbilag.', 'Æsken rammer noget forældre faktisk bruger, men stadig med en gavefølelse.', ARRAY['3 produkter','Babybad-tema','Praktisk og gaveegnet','Kan sendes direkte'], 49, 'live'),
  ('g4', 'premium-barsel', 'Premium Barsel', 'Premium', 'En større barselsgave med Babyly, SoKind og Summerville organic.', 'Til familie, fællesgave eller firmagave.', 'Til den lidt større barselsgave, hvor flere går sammen om noget ordentligt.', 'Firmagave, fællesgave, barsel eller en særlig velkommen-til-verden gave.', 'Pakkes som premium-æske med tekstil, pleje og babyprodukt tydeligt opdelt.', 'Plads til en længere hilsen fra team, familie eller vennegruppe.', 'Velegnet til direkte levering til hjemmet eller arbejdspladsen.', 'Den kombinerer en højere gaveværdi med produkter, der både er pæne og praktiske.', ARRAY['3 produkter','Premium barselsgave','God til fællesgave','Mulighed for længere hilsen'], 49, 'live'),
  ('g5', 'rolig-weekend', 'Rolig Weekend', 'Wellness', 'Naturlig beauty til en langsom weekend og lidt selvforkælelse.', 'Ler, rosenvand og økologiske olier fra More.', 'Til hende, der elsker naturlig beauty, hjemme-spa og lidt tid for sig selv.', 'Fødselsdag, venindegave, tak-for-hjælpen eller selvforkælelse.', 'Pakkes med beautyprodukterne samlet som en lille hjemme-spa gave.', 'Korttekst kan tilføjes, så gaven føles personlig selv ved direkte levering.', 'Kan sendes direkte til modtager eller bestilles hjem til egen overrækkelse.', 'Æsken fungerer som en samlet wellness-gave frem for enkeltprodukter, der bare ligger ved siden af hinanden.', ARRAY['4 produkter','Naturlig beauty','Hjemme-spa følelse','God til venindegaver'], 49, 'live')
on conflict (legacy_id) do update set
  slug = excluded.slug,
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  note = excluded.note,
  recipient = excluded.recipient,
  occasion = excluded.occasion,
  packing = excluded.packing,
  card_text = excluded.card_text,
  delivery = excluded.delivery,
  why = excluded.why,
  details = excluded.details,
  box_price = excluded.box_price,
  status = excluded.status;

insert into public.giftbox_products (giftbox_id, product_id, sort_order)
select gb.id, p.id, item.sort_order
from (
  values
    ('g1','p4',1), ('g1','p13',2), ('g1','p15',3),
    ('g2','p3',1), ('g2','p5',2), ('g2','p6',3),
    ('g3','p8',1), ('g3','p5',2), ('g3','p7',3),
    ('g4','p1',1), ('g4','p3',2), ('g4','p10',3),
    ('g5','p11',1), ('g5','p13',2), ('g5','p14',3), ('g5','p16',4)
) as item(giftbox_legacy_id, product_legacy_id, sort_order)
join public.giftboxes gb on gb.legacy_id = item.giftbox_legacy_id
join public.products p on p.legacy_id = item.product_legacy_id
on conflict (giftbox_id, product_id) do update set sort_order = excluded.sort_order;

insert into public.pages (slug, title, eyebrow, intro, sections)
values
  ('contact', 'Kontakt', 'Kundeservice', 'Har du spørgsmål til en gaveæske, levering direkte til modtager eller hjælp til at sammensætte en gave, kan du kontakte os her.',
   '[{"title":"Kontaktoplysninger","body":"E-mail: hello@greenplanet.dk. CVR: 44640376. Adresse: Bøgevejen 6, 2850 Nærum. Vi svarer normalt inden for 1-2 hverdage."},{"title":"Hjælp til gavevalg","body":"Skriv gerne anledning, budget, ønsket leveringsdato og om gaven skal sendes direkte til modtager."}]'::jsonb),
  ('delivery', 'Levering', 'Kundeservice', 'Greenplanet kan sende gaveæsker direkte til modtager eller til dig, hvis du selv vil overrække gaven.',
   '[{"title":"Levering til modtager","body":"Ved checkout kan du vælge modtagers navn, adresse, ønsket leveringsdato og en leveringsnote. Vi sender uden prisbilag, når gaven sendes direkte."},{"title":"Leveringstid","body":"Lagervarer pakkes som udgangspunkt inden for 1-3 hverdage efter ordrebekræftelse. Den forventede leveringsdato fremgår af den bekræftelse, du modtager fra Greenplanet."},{"title":"Fragt og levering","body":"Fragtprisen vises i checkout, før du sender bestillingen. Levering koster 49 kr., mens afhentning eller særskilt aftalt levering vises som 0 kr. i checkout."},{"title":"Forsinkelse eller fejl","body":"Hvis pakken bliver forsinket eller beskadiget under levering, hjælper vi med at finde en løsning. Kontakt os med ordrenummer og gerne billeder ved transportskade."}]'::jsonb),
  ('returns', 'Returnering og fortrydelse', 'Kundeservice', 'Her finder du Greenplanets regler for fortrydelse, returnering og undtagelser.',
   '[{"title":"Fortrydelsesret","body":"Som forbruger har du som udgangspunkt 14 dages fortrydelsesret ved køb online. Fristen regnes normalt fra den dag, du eller en valgt modtager får varen i fysisk besiddelse."},{"title":"Sådan returnerer du","body":"Kontakt Greenplanet med ordrenummer, navn og hvilke varer du ønsker at returnere. Ved fortrydelse skal varen returneres uden unødig forsinkelse og senest 14 dage efter, at du har givet besked om fortrydelse."},{"title":"Undtagelser","body":"Forseglede pleje- og hygiejneprodukter kan miste fortrydelsesretten, hvis forseglingen brydes. Personlige korttekster, specialpakkede gaveæsker eller varer tilpasset efter dine specifikke ønsker kan være undtaget."},{"title":"Tilbagebetaling","body":"Når vi har modtaget og kontrolleret returneringen, tilbagebetaler vi beløbet til samme betalingsmiddel, medmindre andet er aftalt. Du betaler selv returfragten, medmindre andet er aftalt."}]'::jsonb),
  ('legal', 'Legal', 'Legal', 'Her finder du Greenplanets juridiske oplysninger, handelsbetingelser, privatlivspolitik og cookiepolitik samlet ét sted.',
   '[{"title":"Virksomhedsoplysninger","body":"Greenplanet, CVR 44640376, Bøgevejen 6, 2850 Nærum, e-mail hello@greenplanet.dk."},{"title":"Handelsbetingelser","body":"Handelsbetingelserne gælder for køb og bestillinger hos Greenplanet. De beskriver blandt andet ordreproces, betaling, levering, fortrydelsesret, reklamation og klageadgang."},{"title":"Privatlivspolitik","body":"Privatlivspolitikken beskriver, hvordan Greenplanet behandler kunders og modtageres personoplysninger i forbindelse med bestilling, levering, kundeservice og bogføring."},{"title":"Cookiepolitik","body":"Cookiepolitikken beskriver brugen af nødvendige cookies og eventuelle cookies til statistik eller marketing, hvis sådanne teknologier aktiveres på webshoppen."}]'::jsonb),
  ('terms', 'Handelsbetingelser', 'Legal', 'Disse handelsbetingelser gælder for køb og bestillinger hos Greenplanet.',
   '[{"title":"Virksomhed","body":"Greenplanet, CVR 44640376, Bøgevejen 6, 2850 Nærum, e-mail hello@greenplanet.dk."},{"title":"Bestilling og aftale","body":"Når du sender en bestilling, modtager Greenplanet dine ordreoplysninger og den samlede pris inkl. fragt. Aftalen er bindende, når ordren er bekræftet skriftligt af Greenplanet, eller når betaling er gennemført efter de betalingsoplysninger, du har modtaget."},{"title":"Priser og betaling","body":"Alle priser vises i danske kroner. Fragt vises i checkout, før bestillingen sendes. Betaling sker efter de betalingsoplysninger, der fremgår af ordrebekræftelsen. Der reserveres eller trækkes ikke betaling automatisk på siden, medmindre der senere tilføjes en betalingsløsning."},{"title":"Produkter og gaveæsker","body":"Greenplanet sælger gaveæsker og udvalgte produkter til baby, barsel og personlig pleje. Indhold, farver og emballage kan variere en smule afhængigt af lagerstatus. Hvis et produkt ikke kan leveres, kontakter vi dig med forslag til erstatning eller ændring af ordren."},{"title":"Levering","body":"Gaver kan sendes direkte til modtager eller til bestiller. Ved direkte gavelevering sendes pakken uden prisbilag, når det er muligt. Levering koster 49 kr., medmindre afhentning eller anden løsning er aftalt."},{"title":"Fortrydelsesret","body":"Som forbruger har du som udgangspunkt 14 dages fortrydelsesret ved køb online. Fristen regnes normalt fra den dag, du eller en valgt modtager får varen i fysisk besiddelse. Du skal give Greenplanet besked inden fristens udløb, hvis du vil fortryde købet."},{"title":"Returnering","body":"Ved fortrydelse skal varen returneres uden unødig forsinkelse og senest 14 dage efter, at du har givet besked om fortrydelse. Varen skal returneres forsvarligt pakket og i væsentligt samme stand. Du betaler selv returfragten, medmindre andet er aftalt."},{"title":"Undtagelser","body":"Forseglede pleje- og hygiejneprodukter kan miste fortrydelsesretten, hvis forseglingen er brudt. Personlige korttekster, specialpakkede gaveæsker eller varer, der er fremstillet eller tilpasset efter dine specifikke ønsker, kan være undtaget fra fortrydelsesretten."},{"title":"Reklamation","body":"Købelovens regler om mangler gælder. Kontakt Greenplanet hurtigst muligt, hvis en vare er beskadiget, forkert eller mangelfuld. Send ordrenummer, beskrivelse og gerne billeder, så vi kan vurdere sagen og finde en løsning."},{"title":"Klageadgang","body":"Hvis vi ikke finder en løsning, kan du klage til Nævnenes Hus, Toldboden 2, 8800 Viborg, via naevneneshus.dk. EU-Kommissionens online klageportal kan også anvendes ved køb på tværs af EU."}]'::jsonb),
  ('privacy', 'Privatlivspolitik', 'Legal', 'Vi behandler personoplysninger for at kunne håndtere bestillinger, levering, kundeservice og drift af webshoppen.',
   '[{"title":"Dataansvarlig","body":"Greenplanet, CVR 44640376, Bøgevejen 6, 2850 Nærum, e-mail hello@greenplanet.dk, er dataansvarlig for behandlingen af personoplysninger på webshoppen."},{"title":"Hvilke oplysninger vi behandler","body":"Vi kan behandle navn, e-mail, telefonnummer, fakturaadresse, leveringsadresse, modtagernavn, korttekst, ordreindhold og eventuelle leveringsnoter."},{"title":"Formål og grundlag","body":"Oplysninger bruges til at behandle bestillinger, pakke og levere gaver, sende ordrebekræftelser, yde kundeservice, håndtere reklamationer og opfylde bogførings- og dokumentationskrav. Behandlingen sker blandt andet for at kunne opfylde en aftale, overholde retlige forpligtelser og varetage Greenplanets legitime interesse i drift og kundeservice."},{"title":"Modtageroplysninger","body":"Hvis du sender en gave direkte til en anden person, behandler vi modtagerens navn, adresse og eventuelle leveringsnoter for at kunne levere gaven. Skriv ikke følsomme oplysninger i korttekst eller leveringsnote."},{"title":"Deling","body":"Nødvendige oplysninger kan deles med fragtleverandører, betalingsudbydere, regnskabssystemer, hostingudbydere og tekniske leverandører, der hjælper med drift af webshoppen. Leverandører må kun behandle oplysninger efter aftale og til de relevante formål."},{"title":"Opbevaring","body":"Oplysninger opbevares kun så længe det er nødvendigt for formålet eller påkrævet efter lovgivning. Regnskabsoplysninger opbevares som udgangspunkt i 5 år efter bogføringsreglerne."},{"title":"Dine rettigheder","body":"Du kan kontakte Greenplanet for at anmode om indsigt, rettelse, sletning, begrænsning, dataportabilitet eller indsigelse, når betingelserne for det er opfyldt. Du kan også klage til Datatilsynet."}]'::jsonb),
  ('cookies', 'Cookiepolitik', 'Legal', 'Cookiepolitikken beskriver, hvordan Greenplanet kan bruge cookies og lignende teknologier på webshoppen.',
   '[{"title":"Hvad er cookies?","body":"Cookies er små tekstfiler, der gemmes på din enhed, når du besøger en hjemmeside. De kan bruges til at få siden til at fungere, huske valg eller måle brug af siden."},{"title":"Nødvendige cookies","body":"Greenplanet kan bruge nødvendige cookies og lokal lagring til grundlæggende funktioner som kurv, checkout, sikkerhed og teknisk drift. Disse er nødvendige for, at webshoppen kan fungere."},{"title":"Statistik og analyse","body":"Hvis Greenplanet bruger statistik- eller analyseværktøjer, sker det for at forstå besøg, populære produkter og tekniske fejl. Ikke-nødvendige cookies bruges kun, når det relevante samtykke er indhentet."},{"title":"Marketing","body":"Marketingcookies bruges kun, hvis Greenplanet senere tilføjer annoncering, tracking eller sociale medier-integrationer, og kun efter relevant samtykke."},{"title":"Ændring af samtykke","body":"Du skal kunne ændre eller trække dit samtykke tilbage igen, hvis der bruges samtykkekrævende cookies. Nødvendige cookies kan normalt ikke fravælges, fordi de får siden til at fungere."}]'::jsonb)
on conflict (slug) do update set
  title = excluded.title,
  eyebrow = excluded.eyebrow,
  intro = excluded.intro,
  sections = excluded.sections;
